### ISSUE TITLE
Update Fission Register to ensure email is required

### ISSUE THREAD

**Issue by bechurch** [fission-suite/fission#217]
# Summary
Update the api and the cli to enforce that all users have an email

## Problem
If a user is unable to authenticate then we have no method of retrieving their domains securely

### Impact
Domains could become unusable. Problem gets worse as we add custom domains.

## Solution
Make email required so taht we have a method to verify users

# Detail
1. Update the Database to make email required
2. Update the API to make email required
3. Update the CLI to make email required

**Comment by dholms** [comment]
Email is already required by both the API & the CLI :+1:
