### ISSUE TITLE
Add domain name registration

### ISSUE THREAD

**Issue by bechurch** [fission-suite/fission#218]
# Summary
Currently our model prevents us from doing multi app and or domain structure.
## Problem
A user needs to register multiple accounts to allow for multiple apps

### Impact
Its both annoying, hard to manage and skews our system

## Solution
1. Move all app data to a separate table. This model is owned by one user. A user can own many.
2. Move all domain data to a separate table. This model is owned by a user and a app. Both can own many
3. The API's register functionality should not change
4. Add new route for allowing users to create additional apps

## Concerns
Heroku functionality should not change

**Comment by dholms** [comment]
What is "app data" in this case? User-deployed apps or apps used to sign up (like Heroku)?
For the former, what info is attached to apps besides domain name?
For the latter, I think we discussed this in the past and decided to keep it in the user table

**Comment by bechurch** [comment]
@expede @dholms @icidasset 
Drew up a diagram just to help with my thoughts on how to structure this
![image](https://user-images.githubusercontent.com/1325608/71609255-47c3b480-2b44-11ea-9383-e82d137d8724.png)

Feedback very welcome!

**Comment by expede** [comment]
Oh yeah, long closed
