### ISSUE TITLE
`.fission.yaml` not created sometimes on register

### ISSUE THREAD

**Issue by dholms** [fission-suite/fission#276]
## Problem
If a user registers, but peer retrieval fails (ie, does not have an ipfs daemon running), then their `fission.yaml` file is never created.

## Solution
If a user is registered, they should save their auth credentials regardless. 
_Note: this issue is probably fixed by switching to jwt auth._

**Comment by expede** [comment]
I'm not sure that we've seen this in months. Flagging as a candidate for closing.

**Comment by expede** [comment]
I haven't seen this in literally 2 years. Closing!
