### ISSUE TITLE
Start an IPFS daemon if not running

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#279]
The recommended way to detect if IPFS is running is to run:

```
ipfs swarm addrs
```

From https://github.com/ipfs/go-ipfs/issues/5983 and https://github.com/aragon/aragon-cli/pull/845

I'm documenting this for now when / if we end up running IPFS ourselves in the CLI.

**Comment by jamiehewitt15** [comment]
Are you able to share a code example of how to wait until the IPFS daemon is running? I have tried to write a script based on waiting until  `ipfs swarm addrs` but I have been running into problems with it.

**Comment by bmann** [comment]
Hey @jamiehewitt15 here's a link to the code in Haskell, but this is going to very programming language specific https://github.com/fission-suite/fission/blob/cc8a01208d05802eb05fd9bcbe4b15243c8e4ae6/fission-cli/library/Fission/CLI/Types.hs#L375

Basically, how the PL handles spawning applications and communicates with them at the system level.

Feel free to come by our Discord chat https://fission.codes/discord if you want to talk further, I'm going to close this issue because we do, indeed, install and spawn the go-ipfs daemon ourselves now.
