### ISSUE TITLE
Windows Executable Hangs on WhoAmI. Among other issues

### ISSUE THREAD

**Issue by bechurch** [fission-suite/fission#280]
# Summary
The windows binary runs however its commands that involve the fission.yaml file all fail.

# Detail
This is all thanks to testing from @mktlr. Expect of his findings below:
```bash
> fission
// shows help text

> fission whoami
// computer slowed down
// ctrl+c pressed immediately exits quickly
// ctrl+c pressed 1 minute later exits around minute 4

> fission login
// Auth fail

> fission register
// Auth fail

> wsl fission login
// Using newly created: auth fail
// Using prev created: logged in

# Manually copied .fission.yaml:
> ~/.fission.yaml
// auth fail
> /.fission.yaml
// auth fail
```

**To Reproduce**
1. Download our windows binary file
2. PLace it on you windows path
3. Run `fission login`

**Expected behavior**
It runs

**Comment by expede** [comment]
Works on WSL2
