### ISSUE TITLE
Update CLI to create additional apps with `fission new`

### ISSUE THREAD

**Issue by bechurch** [fission-suite/fission#283]
dependant on: https://github.com/fission-suite/web-api/issues/219

# Summary
Essentially we want users to be able to create multiple apps

### Impact
This will allow users to own and manage multiple apps

## Solution
1. A user types `fission new`
2. We prompt them for an optional app name
3. If no name is given generate a random name
4. We then create a local fission.yaml file with the name of the app and provision a subdomain

### Edge cases
1. ensure all app names would be valid as a subdomain

**Comment by expede** [comment]
Closed by #313
