### ISSUE TITLE
When inspecting a "global" .fission.yaml, I don't know what the username is

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#324]
I have a global fission.yaml file, created by the new key method setup. By inspecting the file, I can't tell what username it is connected to.

I would add the username into the yaml file. Could even be as a comment.

I also note that the new template has an empty ignore. I think `.DS_Store` and `.env` are still good defaults.

**Comment by expede** [comment]
@bmann that's a side effect of having overridable stuff. Have you tried `fission whoami`?

**Comment by bmann** [comment]
@expede I understand `fission whoami`, although in this case I was troubleshooting because it was throwing an error telling me I wasn't logged in. The issue still remains. Any `fission.yaml` file can't be inspected, especially if it's in a sub-folder somewhere, to see what username it is connected to.

Not high priority, just logging stuff like this.

**Comment by expede** [comment]
@bmann is this still a concern now that we don't need a workaround for multi-app?

**Comment by expede** [comment]
Fixed in v2.9.0
