### ISSUE TITLE
Set name of app as part of init

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#350]
The current `app-init` command automatically selects an app name / subdomain as part of running.

As a user, I would like to init a new app with a custom subdomain of my choice.

Something like `fission app-init --name my-cool-name` (it needs to be a valid subdomain string, so kebab case only if you want separators!).

We may take this opportunity to do `fission app init --name`, thus also setting up for `fission app` to list all apps for current account (which is what I think the default should be).

This will need to check for validity (can do this local in CLI) and availability (check against server endpoint if subdomain is available).

If not valid -- "🤭 App names needs to be a valid subdomain, less than XX chars, hyphens. How about `new-sub-domain`?" <enter to accept or try another subdomain>

If not available -- "😭 Sorry! Someone else already has an app using that subdomain. How about `new-sub-domain`?" <enter to accept or try another subdomain>

Skip `<enter to accept or try another subdomain>` if that's complicated. Mainly clear messaging and making it easy for people, just trying to come up with some default message.

Future thoughts:
* For offline usage compatibility, we skip availability, show error message on fission up, generate new valid name, and complete publishing.
* User can set / rename the default subdomain (future feature!)

**Comment by bmann** [comment]
@expede has it live on staging!

@icidasset assigned to you to test and try!

**Comment by icidasset** [comment]
Tested this and works 👍 
Made [quotes.fission.app](https://quotes.fission.app) and [drive.fission.app](https://drive.fission.app) 🎉
