### ISSUE TITLE
Add prefix to TXT records so we can join them in order

### ISSUE THREAD

**Issue by icidasset** [fission-suite/fission#352]
## Problem

When we lookup a user's root DID using the `_did.username.fission.name` domain, the DID is split into multiple TXT records (in the case of an RSA DID). The problem is that the order of these records is random, sometimes the first record is `did:key:...`, other times it's a different part of the DID. Tested with https://dnsrecords.io and the `dig` command.

## Solution

Add an ordering prefix to the record.
For example: `1:2:qQxvcYxBbJZ51qc5FWGu8u5Vcgh4G78CnD2AAkfXp35rsjuAAYCcqvKREdGBUe6GADyp1FRGvePwnixamyjkoyQtmpgJFHudRXH`.
Format: `which_key:which_part:chunk`

**Comment by expede** [comment]
It would also lower the parsing overhead to have a fixed size header. We know that TXT can take up to 255 fields. We can either count in hex or decimal:

Decimal:
```
001;did:key:z12345
220;did:key:z12345
```

Hex
```
01;did:key:z12345
DC;did:key:z12345
```

**Comment by dholms** [comment]
Cool I like just the one number (and finding key breaks by looking for `did:key` or similar) & using a semicolon as a delimiter to avoid confusion

> hex or decimal

my initial reaction was hex just cause we're in crypto-land and things are seldom in decimal + slight space savings. but as you said it doesn't really matter, and it's only one character. And it's prefixed in front of the human readable "did:key" so it would also make sense to have the index be a human readable decimal number

**Comment by dholms** [comment]
Follow up question:

**Comment by dholms** [comment]
oh also 0-indexed or 1-indexed?

**Comment by expede** [comment]
> oh also 0-indexed or 1-indexed?

Yeah, good point. For sure 0-indexed 💯

> I'll probably start on decimal unless I hear otherwise

Decimal is also my feeling on this. Let's just manage it in software. Pretty easy to keep it straight on that side, PLUS we can't put more parts than TXT allows, so great
