### ISSUE TITLE
500 error on PUT /user

### ISSUE THREAD

**Issue by icidasset** [fission-suite/fission#356]
# Summary

## Problem

Getting a 500 HTTP error status on `PUT /users` using the following on **staging**:
```
{"email":"icidasset+test-11@gmail.com","username":"icidasset-test-11"}
```

It seems like it added the user to the database because when I try to register another account with the same DID I'm getting the correct `409` status.

Sentry link: https://sentry.io/organizations/fission-suite/issues/1716369761/?project=1802980&query=is%3Aunresolved

**Comment by expede** [comment]
Troubleshooting notes:

Looks like its blowing up when trying to write to the TXT record.

```
2020-07-16 18:32:50.949169: [debug] (SQL) SELECT "id", "public_key", "email", "username", "role", "active", "verified", "data_root", "heroku_add_on_id", "secret_digest", "inserted_at", "modified_at" FROM "user" WHERE ("id"=?) AND ("active"=?) LIMIT 1; [PersistInt64 41,PersistBool True]
@(<unknown>:0:0)
2020-07-16 18:32:50.949732: [debug] Updating DNS record at: _did.icidasset-test-11.fissionuser.net
@(<unknown>:0:0)
2020-07-16 18:32:51.247514: [error] 172.31.79.97:63138 - - HTTP/1.1 - - 500: "Internal Server Error" "PUT"
```

**Comment by expede** [comment]
* Route53 credentials look fine (NOTE: I didn’t go characer-by-character).
* We really should get the database transaction to roll back if other actions fail
  * Not always possible, but the more the better really

**Comment by expede** [comment]
@icidasset a couple questions:

* Is this issue persistent, or only sometimes?
* Someone mentioned that everything works via the CLI? This is only via the SDK?
* Does the issue persist on production?

**Comment by icidasset** [comment]
<img width="906" alt="Screenshot 2020-07-16 at 22 11 45" src="https://user-images.githubusercontent.com/296665/87717865-63756c00-c7b1-11ea-8f5b-bb76ea703845.png">
Happens on productions as well ☝️ 
(also ignore that CORS report, that's just because of the missing header, because 500 error)

Issue is constant, have tried with multiple fresh DIDs and usernames & emails (well roughly different email, just changing a number after the `+`).

**Comment by expede** [comment]
That is... very weird. Prod hasn’t been updated, and was definitely working before. I wonder if our AWS credentials have been invalidated or something?

**Comment by expede** [comment]
Oh, wait, this is at `auth.`. I guess I should check the CLI

**Comment by expede** [comment]
Okay, this in fact _does_ work on the latest CLI on staging. Something is breaking with the request originating from the browser.

We should definitely make the DB roll back if this fails along the way, but good to be narrowing the problem space

**Comment by expede** [comment]
Hmmm, one difference could easily be that the CLI uses a Ed215519 key (much shorter), and the browser uses a RSA2048 key that needs to be broken up. Route53 may be rejecting the TXT array.

**Comment by expede** [comment]
Double checked assumptions: no email challenge token was created, and no DNS entry created, so confirmed failing at Route53.

**Comment by expede** [comment]
Ah, this also explains why it doesn’t like this on prod. An RSA key is too long for a TXT record.

**Comment by dholms** [comment]
This is likely an issue with the recent PR that splits up TXT records. I'm sizing TXT records to be 256 chars, but the max size is 255. Putting a fix up shortly
