### ISSUE TITLE
Resend Verification

### ISSUE THREAD

**Issue by dholms** [fission-suite/fission#359]
## Problem
Verification emails are only sent on account creation. They can't be sent ad-hoc

### Impact
- If a user loses their verification email, we have to manually verify them
- Any user that is already in our DB has to be manually verified

## Solution
Add a route to resend a verification email

**Comment by dholms** [comment]
This is a relatively quick add, but I imagine low-priority. Thoughts @bmann?

**Comment by bmann** [comment]
Yeah good call. We’ll want to expose this a couple of places.

**Comment by matheus23** [comment]
Whoops, this is implemented since #435
