### ISSUE TITLE
Extend the IPFS Github Action to make a Fission Github Action

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#360]
The [IPFS Github Action in ipfs-shipyard](https://github.com/ipfs-shipyard/ipfs-github-action) is a good base to build on. We may be able to PR back Fission support.

It expects an IPFS Cluster. Instead, we'd use a call to Fission's HTTP endpoint, and store credentials (public key, I think?) of a user account in secrets.

Also need to indicate which app it's for in a `fission.yaml`, as well as potentially ignore and other settings.

**Comment by walkah** [comment]
This is being handled in https://github.com/fission-suite/publish-action
