### ISSUE TITLE
fission-cli expects ipfs to be installed at /usr/local/bin/ipfs

### ISSUE THREAD

**Issue by fubuloubu** [fission-suite/fission#361]
# Summary
- Version: 2.4.2
- OS: Ubuntu 20.04 LTS
- IPFS: 0.6.0-d6e036a88 (installed via `snap`)

## Problem
`fission-cli` expects ipfs to be installed at `/usr/local/bin/ipfs`, but `snap install ipfs` installs it at `/snap/bin/ipfs`

### Impact
Can't run tool

## Solution
Probably shouldn't assume location of installed program, maybe query via `which ipfs` instead

**Comment by fubuloubu** [comment]
Thanks bot

**Comment by bmann** [comment]
You can set IPFS_PATH https://guide.fission.codes/hosting/cli#additional-settings

Linux is frustratingly complex to support reliably. Long term plan is to bundle IPFS into the CLI.

**Comment by expede** [comment]
What @bmann said. @fubuloubu, if you could confirm that  the IPFS_PATH works for you, we can close this issue.

_That said_, maybe we should `which ipfs` and use that path unless overwritten 🤔

**Comment by expede** [comment]
That would be trivial — I may do that right now
