### ISSUE TITLE
Return non-zero exit code on failures.

### ISSUE THREAD

**Issue by matheus23** [fission-suite/fission#381]
# Summary

When, e.g. `fission up` fails, return a non-zero exit code, such as `1`. This makes it easier to use `fission up` for scripting.

## Problem

`fission up` returns exit code 0, even when it fails, e.g. when it fails with:
```
$ fission up
🚫 Server unable to sync data
$ echo $?
0
```

### Impact

Using `fission up` in e.g. bash scripts is a little annoying.

## Solution

Return an exit code other than 0, when there's an error.

**Comment by expede** [comment]
Yup, totally makes sense 👍

**Comment by matheus23** [comment]
Yay :) Thanks @walkah
