### ISSUE TITLE
Let CLI user know when their email is invalid

### ISSUE THREAD

**Issue by expede** [fission-suite/fission#384]
NB: Feature requests will only be considered if they solve a pain

# Summary

## Problem

At time of writing, if email verification cannot be sent (e.g. malformed email address), we return a generic `HTTP 500`. It would be good to return a `422` and message about being unable to send the verification email. Also should probably revert the account, too.

### Impact

* Harder to debug
* Confusing for the user when it fails

## Solution

* 500 -> 422
* Descriptive message

**Comment by erlandsona** [comment]
Same question as https://github.com/fission-suite/fission/issues/429#issuecomment-826236047

**Comment by expede** [comment]
Same answer 😉
