### ISSUE TITLE
Make additional app data from web API

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#385]
@nathanmalishev is building a dashboard. Additional data about an app would be useful:

- creation date
- date of last update

**Comment by erlandsona** [comment]
@expede seems like this info is already stored in the db @ [Web/Server/Models.hs](https://github.com/fission-suite/fission/blob/main/fission-web-server/library/Fission/Web/Server/Models.hs#L146)
But given the dependency structure is there a mapping layer between the db representations and what's currently exposed by [API/App/Index/Types.hs](https://github.com/fission-suite/fission/blob/main/fission-web-api/library/Fission/Web/API/App/Index/Types.hs).

My assumption is API shouldn't/can't (for whatever reason) depending on Models defined in server based on the project structure. But in this case it'd be super convenient to pull in the db rep and add the Generic `json` instances generated by persistent?

I'm probably just being naive here but something like [this](https://bitbucket.org/erlandsona/resourcery/src/53c4435e885aa3160afd61a57d22ec4e0926bb60/library/Models.hs#lines-42)?

**Comment by expede** [comment]
@erlandsona

There is no direct mapping from the DB directly to the exposed API. Coupling the DB to the external API is not a great idea in an API like ours that needs to evolve over time. We need the manual control of things like key naming and backward-compatible deserializers has been really helpful. We also have access control on the endpoints, with more granular access coming. We had started with `Generic` instances, but it ended up actually causing more problems than it solved for our use case. Luckily writing Aeson instance by hand is pretty straightforward :)

**Comment by erlandsona** [comment]
The coupling piece makes sense and I've heard it before (back when I didn't really understand how to write decoders/encoders)... but fortunately now, that concept (decoders/encoders) has sunk in so I'm probably more inclined to understand why manual Aeson instances are better for this use case.

> Plus there's some advantage to putting a class in between for docs, development, access control, and test mocks, but that's a separate topic that I'd be happy to get into next week

I feel like I saw that while hoppin' around and I was like whoa :exploding_head:. 
Can't wait to level up!
