### ISSUE TITLE
Simple "Magic" command(s)

### ISSUE THREAD

**Issue by dholms** [fission-suite/fission#386]
Something we talked about on our call today:

There's something nice about the brevity of `fission up`. I remember being pretty wowed running `now` (from zeit) for the first time. I'm not sure that same magic would be there with long commands like `fission app publish`.

What commands could we add that would give that same "magic" feeling?

We talked about, for instance, a simple `fission` cmd that would walk you through setup, app init, & app up all in one. Maybe a TUI?

**Comment by bmann** [comment]
As discussed — just `fission` (or win or whatever) should “do the right thing”. 

Long form commands are for experts or for other shell commands to call.

**Comment by walkah** [comment]
Started #442 to tackle this, which more deals with shortcuts defaulting to help text so far.

What does everyone thing just `fission` *should* do?

**Comment by expede** [comment]
Closed #442
