### ISSUE TITLE
UCAN v1.1

### ISSUE THREAD

**Issue by icidasset** [fission-suite/fission#387]
Currently working on a SDK PR that implements the following.

## Access to file system

Use case: application needs a place to store application data.

```
rsc: { dnslink: "username.fission.name/private/Apps/icidasset/Quotes" }
ptc: "*"
```

## Fission Dashboard

Has access to, everything?

```
rsc: "*"
ptc: "*"
```

## Other resources/potencies?

I'll add some constants to the SDK for other resources and potencies, but I don't know what they are.

### Resources

- `*`
- `{ dnslink: "username.fission.name/path" }`

### Potencies

- `*`
- `APPEND`
- `DESTROY`

**Comment by expede** [comment]
Updated in whitepaper

https://whitepaper.fission.codes/access-control/ucan/webnative-attenuation
