### ISSUE TITLE
Show message when build_dir is auto detected

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#389]
When I app init (or when I fission up, not sure?), the correct build_dir is auto detected and set to `./dist`

However, it does this silently. Should print out:

```
./dist detected and set as build_dir in .fission.yaml. When you fission up, the contents of this folder will be uploaded
```

**Comment by dholms** [comment]
:+1: I actually posted something similar in @expede's PR

We discussed this on our call, but just to get it written down: 
Use `checkBuildDir` instead of `guessBuildDir` & it will prompt the user to check that they want to set the build dir
