### ISSUE TITLE
CLI Account linking

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#390]
This is an issue to track linking of accounts involving the CLI.

## CLI to CLI Linking

I am on a new machine and have downloaded the CLI. I would like to link this account to an existing one. 

Fission setup explains that the username / email combo is available, and proceeds to give instructions on what to do on the other machine. 

It is live and running and shows “waiting for link” or similar.

On the second machine, Fission link command in the CLI? With a number — eg `fission link 12345`

### I have the CLI installed and would like to link to a local web browser. 

Slightly different instructions involving opening up auth page?

### I have a web browser account and would like to link the CLI

`fission link 12345` should work here.

**Comment by lifeiscontent** [comment]
@bmann any updates here? I'd love to explore fission but this is blocking me from getting started.

**Comment by expede** [comment]
Literally cleaning up the PR right now

**Comment by matheus23** [comment]
> I have a web browser account and would like to link the CLI

This has landed with version 2.10.2: https://github.com/fission-suite/fission/releases/tag/2.10.2

**Comment by expede** [comment]
We're still waiting on #486 and EdDSA support in the WebNative SDK (no PR yet)
