### ISSUE TITLE
Stop logging ELB/2.0 status pings

### ISSUE THREAD

**Issue by expede** [fission-suite/fission#393]
I thought that we did this already, _but apparently not._ ELB checks for health every 5 seconds or so, making finding actual data in the logs much noisier.

(Also should remove any colour from what gets reported to Sentry for noise reasons as well). We can make that split pretty easily in the same part of the code IIRC.

**Comment by erlandsona** [comment]
? https://github.com/fission-suite/fission/blob/e2955f61a55b61ffff0d9acb661555d22b565dfb/fission-core/library/Fission/Web/Log.hs#L21

**Comment by expede** [comment]
Yes, but they're still showing in the logs
