### ISSUE TITLE
lzma-0.0.0.3 fails to build while building fission-cli

### ISSUE THREAD

**Issue by bgins** [fission-suite/fission#408]
# Summary

When building the `fission-cli`, the build fails when `stack` attempts to build `lzma-0.0.0.3`.

## Problem

The CLI does not build on Ubuntu 18.04. Or at least not on my machine, hard to say whether this true in general.

### Impact

I am unable to build the CLI.

## Solution

Uncertain what a solution might be here.

# Detail

**Describe the bug**

While building `fission-cli` using `stack`, the following build error occurs.

```
--  While building package lzma-0.0.0.3 using:
      /home/thuselem/.stack/setup-exe-cache/x86_64-linux/Cabal-simple_mPHDZzAJ_3.0.1.0_ghc-8.8.3 --builddir=.stack-work/dist/x86_64-linux/Cabal-3.0.1.0 configure --user --package-db=clear --package-db=global --package-db=/home/thuselem/.stack/snapshots/x86_64-linux/d398b147a9dde2194168d48f95c0795080d87b6dfa3b16a82b1a98acfc845a03/8.8.3/pkgdb --libdir=/home/thuselem/.stack/snapshots/x86_64-linux/d398b147a9dde2194168d48f95c0795080d87b6dfa3b16a82b1a98acfc845a03/8.8.3/lib --bindir=/home/thuselem/.stack/snapshots/x86_64-linux/d398b147a9dde2194168d48f95c0795080d87b6dfa3b16a82b1a98acfc845a03/8.8.3/bin --datadir=/home/thuselem/.stack/snapshots/x86_64-linux/d398b147a9dde2194168d48f95c0795080d87b6dfa3b16a82b1a98acfc845a03/8.8.3/share --libexecdir=/home/thuselem/.stack/snapshots/x86_64-linux/d398b147a9dde2194168d48f95c0795080d87b6dfa3b16a82b1a98acfc845a03/8.8.3/libexec --sysconfdir=/home/thuselem/.stack/snapshots/x86_64-linux/d398b147a9dde2194168d48f95c0795080d87b6dfa3b16a82b1a98acfc845a03/8.8.3/etc --docdir=/home/thuselem/.stack/snapshots/x86_64-linux/d398b147a9dde2194168d48f95c0795080d87b6dfa3b16a82b1a98acfc845a03/8.8.3/doc/lzma-0.0.0.3 --htmldir=/home/thuselem/.stack/snapshots/x86_64-linux/d398b147a9dde2194168d48f95c0795080d87b6dfa3b16a82b1a98acfc845a03/8.8.3/doc/lzma-0.0.0.3 --haddockdir=/home/thuselem/.stack/snapshots/x86_64-linux/d398b147a9dde2194168d48f95c0795080d87b6dfa3b16a82b1a98acfc845a03/8.8.3/doc/lzma-0.0.0.3 --dependency=base=base-4.13.0.0 --dependency=bytestring=bytestring-0.10.10.0 --exact-configuration --ghc-option=-fhide-source-paths
    Process exited with code: ExitFailure 1
```

**To Reproduce**
1. Install `stack` and `postgresql` as described in the README
2. Attempt to build with `stack build --no-nix fission-cli:fission`

I have `stack` v2.3.3 and `postgresql` v12.4, and I am building on `master` at e2955f61a55b61ffff0d9acb661555d22b565dfb.

After searching around a bit, I thought it might be possible I might have an out of date package cache, and I added a couple of flags, but the build still fails.

```
stack build --no-nix --no-system-ghc --install-ghc fission-cli:fission
```

**Expected behavior**

The build succeeds.

**Desktop (please complete the following information):**
 - OS: Ubuntu
 - Version: 18.04

**Comment by expede** [comment]
Yeah, you need to have lzma-dev installed on your system. I’ll dig up the exact package for Ubuntu

**Comment by expede** [comment]
Via @dholms 

> we have these 2 listed in the guide: `apt install libpq-dev libtinfo5`

**Comment by expede** [comment]
from the lmza repo, and matches my memory:

> apt install liblzma-dev

**Comment by dholms** [comment]
yeah I haved `liblzma-dev` installed. Give that a go!

**Comment by bgins** [comment]
That did it! The build succeeded with that installed. Thanks for the help!
