### ISSUE TITLE
Improve build dir detection wording

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#420]
The CLI auto-detects a build dir and fills it in, and the user just has to hit enter. I think just saying "build dir" is a little brief, maybe something like:

(if detected)
```shell
BUILD_DIR_PATH auto-detected. Hit Enter to accept, or enter different build folder path:
```

(if not detected):
 ```shell
No build folder auto-detected. Hit Enter to use the current dir or enter build folder path
```

**Comment by bmann** [comment]
cc @dannyrobinson

**Comment by dannyrobinson** [comment]
Maybe “Choose Build Directory” - try to ensure that every prompt has the verb of the action required

"Type" "Choose" "Pick" "Enter". - all work.  But for the record, I also think I'm an idiot for getting it confused as is... I'm glad I can act as your lowest common denominator here.

**Comment by bmann** [comment]
That guidance of having a verb is really good. I know that the emojis are on point, but the actual wording of prompts and messages need a good overview across all of the commands. Thanks @dannyrobinson!

**Comment by walkah** [comment]
This was changed in #421
