### ISSUE TITLE
Copy site URL to clipboard  / Open after publish

### ISSUE THREAD

**Issue by walkah** [fission-suite/fission#429]
# Summary

Add some simple convenience options for opening / using the newly generated domain in a browser. There were a few options suggested:

- [ ] After publish (or register?) copy the generated URL to the user's clipboard (where accessible)
- [ ] Add a `--open` (or the github CLI uses `--web`) switch that would automatically open the URL in the browser

**Comment by erlandsona** [comment]
@expede think I've got some code ready for this... do y'all want to add me to the repo so I can just push my branches for a PR or fork and PR?

**Comment by expede** [comment]
@erlandsona you can also fork the repo and make a request cross repository: https://docs.github.com/en/github/collaborating-with-issues-and-pull-requests/creating-a-pull-request#changing-the-branch-range-and-destination-repository
