### ISSUE TITLE
Email verification link which has already been verified shows message "user not found"

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#439]
If you click on a verified email link a second time, the user sees "User not found" as an error, when in fact the user is already verified.

For now, change this to "User already verified -- you're good to go!" or similar error-y string.

Redirecting to AUTH or DASHBOARD could be the right product flow to do in the future.

**Comment by bmann** [comment]
Forgot to mention, via @trishussey

> How about you say “Yep, you’re all good” or something like that if they verify or are already verified. If there is an error the go with the “something doesn’t look right here, ping for help” or something.

**Comment by bmann** [comment]
Other reports that the main verification email link shows as "user not found".

I tried to reproduce, created new account, got verification email, works no problem. Clicking on the verify email in my email and it still shows as verified every time.

Pasting the _same_ link into a second browser (one without the device linked) and I get `user not found`. So, looks like this is incorrectly checking link status.

Thanks @flancian!

**Comment by matheus23** [comment]
This was fixed here:
https://github.com/fission-suite/fission/pull/456/commits/57f71da18ba01453581df3c56f69350bc49acc70#diff-b81d61b9d0381ea0d20d993fd571e3680c6839576b61b0a00f64e4c4401e4aeaL26-R26
