### ISSUE TITLE
Support bash/zsh/fish completions

### ISSUE THREAD

**Issue by walkah** [fission-suite/fission#441]
Make it easy for CLI users to navigate our commands by offering shell completion.

e.g. 
```shell
$ fission u<TAB>
```

would complete to `fission user`

**Comment by expede** [comment]
@walkah Technically this exists, but we should maybe add it to `fission setup` or the installer?

```bash
$ source <(fission --bash-completion-script `which fission`)
$ fission user register
```

Works on my machine:tm:

See this section in the optparse-applicative docs: https://www.stackage.org/lts-17.9/package/optparse-applicative-0.15.1.0#bash-zsh-and-fish-completions

Thoughts?

**Comment by matheus23** [comment]
It looks like usually you'd install bash completion scripts in `/usr/share/bash-completion/completions`. However, we don't know whether fission is installed machine-wide or only in the user's home.

I guess ideally there'd be a package manager package for each distribution that installs the completion script in the correct directory. But, yeah just read that sentence :D

**Comment by walkah** [comment]
If I remember right, I jotted this down during a call and we wanted to see if it worked, @expede so the answer is: yes! 😁 

Yeah, most package managers (homebrew and nix for sure) have a mechanism for installing completion files... so I think this issue can be "install shell completions under nix" and I'll open a similar one for homebrew.

**Comment by expede** [comment]
>  we don't have issues enabled on the homebrew repo

@walkah ...maybe we should?

**Comment by walkah** [comment]
Added this to the homebrew package. As we package for other distributions/platforms we can add there as we go.

<img width="509" alt="Screen Shot 2021-04-23 at 1 14 37 PM" src="https://user-images.githubusercontent.com/15350/115907138-74d16000-a436-11eb-9be7-df0e063b83ae.png">
