### ISSUE TITLE
Authorization to connect needed on MacOS Catalina

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#443]
Fernando Aires:

> I'm using fission on MacOS (Catalina) - installed via brew, today -, and using the CLI it pops *several* messages saying that fission-ipfs needs authorization to connect, for every operation I try to do. I found fission-ipfs on ~/.config/fission/bin/, and manually adding it on socketfilterfw --unblockapp doesn't seem to solve the issue. I didn't find anything on docs about it, and although this is probably a macos-related issue, since it's happening only with fission usage I thought this would be a good place to ask. Anyone found similar problems? How did you solve it?

**Comment by expede** [comment]
I don't think that we've seen this since, though I could absolutely be wrong! Leaving here for now, but flagging for removal unless we come across it again. Will check with the support team!

**Comment by bmann** [comment]
Not reproducible.
