### ISSUE TITLE
Messages from fission-cli unreadable in terminals with light mode themes

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#458]
This is what our success after `fission publish` looks like:

![light-terminal-unreadable](https://user-images.githubusercontent.com/280420/108569993-c6882d80-72c1-11eb-9531-c9eff6ebc95f.png)

Need to set some other defaults that are readable in light mode.

Thanks @edalzell

**Comment by expede** [comment]
hmmmm good point 🤔 

It's amazing that we've literally never seen this on a light background until now 😅

**Comment by matheus23** [comment]
Yellow carries this kind of "warning" meaning, so I didn't just want to switch to something else, especially for some of the warning messages we have in yellow.

However, there's "vivid" and "dull" yellow. This is what the colors look like for me in my `gnome-terminal` with adawaita light/dark theme:
![image](https://user-images.githubusercontent.com/1430958/108891917-94533480-760f-11eb-9104-88b37570f19b.png)
![image](https://user-images.githubusercontent.com/1430958/108891991-a503aa80-760f-11eb-8187-e8051fbf2a44.png)

The top one is dull the bottom one is vivid yellow.

In my terminal, yellow is fine both ways. Ideally, the terminals should themselves adjust their colors based on the theme to stay readable (it's not like we're using custom rgb values for the colors).

Anyway, I propose we change to dull yellow and hope that it looks fine for people with dark theme terminals?

**Comment by expede** [comment]
Yeah, that's a good point about the terminal should have sensible defaults. This is why themes come with named colour sets. @bmann do we know which theme he's using? I just looked at the macOS defaults, and none of them look like that:

<img width="228" alt="Screen Shot 2021-02-23 at 11 06 24 AM" src="https://user-images.githubusercontent.com/1052016/108894479-300c8280-75c7-11eb-80c3-c64e1222f745.png">

---

I don't think that this case is meant as a warning, more as info ("hey, next you may want to run these"). But yeah, yellow warning text is definitely a thing.

---

Aside: we should probably make this interactive and ask "do you also want to publish now?"

**Comment by edalzell** [comment]
> @bmann do we know which theme he's using

Pretty sure it's this one: https://github.com/sindresorhus/pure

**Comment by expede** [comment]
That looks like a prompt (characters), not a theme (colours). In any case, we're changing some of the colours to 1. be more meaningful, and 2. hopefully show better on a wider variety of themes 👍 (though we can't control for every theme)
