### ISSUE TITLE
Allow underscores in usernames & subdomains

### ISSUE THREAD

**Issue by expede** [fission-suite/fission#467]
NB: Feature requests will only be considered if they solve a pain

# Summary

## Problem

Today, users are restricted to non-underscored usernames and app names (subdomains).

We need to blocklist `_did` and `_dnslink` if not already done.

### Impact

People can't pick valid usernames. It's annoying 😛 

## Solution

Allow underscores in the validator

**Comment by dholms** [comment]
Closed here: https://github.com/fission-suite/fission/pull/468
And in the sdk: https://github.com/fission-suite/webnative/pull/180
