### ISSUE TITLE
CLI Linking feedback

### ISSUE THREAD

**Issue by bmann** [fission-suite/fission#478]
Verbose mode, spelling of bearer token: `Decrypted still-serialized brearer token:`

When prompted with `Do you have an existing account? [Y/n]`, I believe convention is that capitalized item is selected if you hit return.

After asking for username, there is no prompt to the user that says "open auth.fission.codes to confirm codes and link your account". Here's where we could attempt to pop a browser directly, but that's a future feature. For now, have to put a message in for sure. The one time I didn't have the browser window already open, it also didn't work (non verbose mode, so no idea what was going on ... I force quit and ran again).

Installing dependencies in non verbose mode takes about 2 minutes. Most of this time is waiting for the IPFS node to boot up for the first time (it can take a while on publish as well). Should do messages to the user like:
* Installing dependencies
* IPFS server downloaded
* Setting config for IPFS server
* Starting IPFS server for the first time

Or, just keep adding to the dots ...............

Confirmation code and linking was very quick and felt like it completed instantly. Woot!

**Comment by expede** [comment]
>  I believe convention is that capitalized item is selected if you hit return

@bmann would you prefer to hit `return` for yes, or to see a lowercase `y`? It's fine by me either way, but I'm leaning towards `return`.

**Comment by bmann** [comment]
Yeah, I think just hitting return is the easy one here.
