### ISSUE TITLE
Discussion: How we handle 'impure' exceptions in the server's route handlers

### ISSUE THREAD

**Issue by matheus23** [fission-suite/fission#491]
Something I noticed when writing #488.

This issue is a call for discussion on how and where to best implement a 'safety-net' for impure exception that might occur 'during' route handlers.

### What are impure exceptions?

I'm not 100% sure how to best call them, so I'll explain what I mean shortly:

A.k.a. "IO Exceptions", because they can be caught in the IO. However, they can be triggered everywhere, also outside IO, e.g. `1 / 0` will trigger an impure exception - or any other partial function.

### How do we handle them?

Catching impure exceptions in haskell is tricky because of laziness.

Something like this won't actually catch the exception:

```hs
> let x = return (1 `div` 0) `catch` handler in ()
```
Similarly, if you only use the value beyond your 'catch' safety-net, then the handler won't run.
More info: https://stackoverflow.com/questions/11149876/how-do-laziness-and-exceptions-work-together-in-haskell

In our case this means that if we try to catch exceptions in handlers outside where response bodies are forced, we might not actually catch them all (no pun intended).

### What happens when an impure exception isn't caught?

If a request generates an exception, it'll be (at the very latest) caught in [warp's exception handler](https://hackage.haskell.org/package/warp-3.2.23/docs/Network-Wai-Handler-Warp.html#v:setOnException).
However, this will bypass all our middlewares. So that's where our CORS issues stem from: We get internal server errors -> warp generates a basic response for them ([this one](https://hackage.haskell.org/package/warp-3.2.23/docs/Network-Wai-Handler-Warp.html#v:defaultOnExceptionResponse), to be exact), but it doesn't include any CORS headers, so it'll fail to appear on the user side.

### How should we catch impure exceptions?

You might say "just don't ever throw impure exceptions! Never write partial functions or divide by zero!".
Well, I think that's really hard, given you don't have control over all code. E.g. `amazonka` can throw exceptions. What we really want is a safety-net.

So there's two way I can think of to fix this:
1. We force response bodies in a middleware and try to catch everything there is (using `deepseq`).
2. Adapt warp's `setOnException` setting to include CORS headers. But this might bite us in the long run, if we expect our middlewares to always run.

I'm interested about your thoughts.

**Comment by expede** [comment]
Fixed by #492
