### ISSUE TITLE
Quick and Dirty AES Key Export Code Snippet

### ISSUE THREAD

**Issue by expede** [fission-suite/fission#495]

**Comment by matheus23** [comment]
Oh, I think I have this in my notes:
```js
await webnative.keystore.getKeyByName(`wnfs__readKey__${await webnative.keystore.sha256Str("/private")}`)
```
This should work when run in the auth lobby/drive.

**Comment by expede** [comment]
FYI @walkah

**Comment by matheus23** [comment]
What I learned today: If you don't have access to private files (e.g. when you're running this from within some other app with fewer permissions), then it'll just generate a new key. In other words, in that case it's confusingly useless :smile:

**Comment by expede** [comment]
> What I learned today: If you don't have access to private files (e.g. when you're running this from within some other app with fewer permissions), then it'll just generate a new key. In other words, in that case it's confusingly useless 😄

Oooooooh that's indeed confusing. We may want to wrap that in a tag, something like:

```ts
{existing: "mywnfskey"}
{generated: "newwnfskey"}
```

Thoughts?

**Comment by expede** [comment]
_Or_ maybe better, it would be good to have separate methods for `getOrGenerate` versus `getExisting`

**Comment by matheus23** [comment]
Alternative:
```js
{ key: ...
, generated: true
}
```
(Whoops excuse the Elm syntax)

> Or maybe better, it would be good to have separate methods for getOrGenerate versus getExisting
Yup. Agree

And possibly support both.
