### ISSUE TITLE
Metadata wrapper

### ISSUE THREAD

**Issue by expede** [fission-suite/fission#50]
# Problem

It's difficult to tell what's in a hash, for when it's being served or searched through

# Solution

Tracking additional information like filesize, MIME type, &c

```haskell
-- Pseudocode
fileHash <- IPFS.add (myFile ^. bytes)
topHash  <- IPFS.add DIR{ file = fileHash
                        , size = myFile.size
                        , mime = myFile.extension
                        -- &c
                        }
```

**Comment by MCTaylor17** [comment]
I was just testing some gateway stuff and noticed a slight behaviour quirk between runfission.com and ipfs.io:

https://runfission.com/ipfs/QmUqd8DGwdL64sZoVy92HRZJwChWGSZEB4zy2GMs8gzYDX
https://ipfs.io/ipfs/QmUqd8DGwdL64sZoVy92HRZJwChWGSZEB4zy2GMs8gzYDX

The runfission.com gateway will download the file whereas ipfs.io will display it.

I'm not certain if that is related to this issue, but it seems related.  I'm thinking the ipfs.io gateway uses a "magic number" checker to detect the MIME before serving.

**Comment by expede** [comment]
Now handled with WNFS
