### ISSUE TITLE
Upgrade ucan-hs to latest UCAN spec

### ISSUE THREAD

**Issue by expede** [fission-suite/fission#562]
**NOTE: Please move Issue this to the standalone repo when it exists**

Spec:
* https://whitepaper.fission.codes/access-control/ucan/jwt-authentication

Depends on:
* https://github.com/fission-suite/fission/issues/563

Related but out of date:
* https://github.com/fission-suite/fission/pull/410

**Comment by expede** [comment]
Depends on https://github.com/fission-suite/fission/issues/563

**Comment by matheus23** [comment]
Closed by #588
