### ISSUE TITLE
Provide precompiled binary release for Mac's M1 ARM architecture

### ISSUE THREAD

**Issue by LesnyRumcajs** [fission-suite/fission#589]
# Summary
Provide binary for Apple Silicon in the releases

## Problem
The new Macs now run on an ARM architecture. The workaround is to run them via Rosetta emulation but it's just a nasty workaround (you'd need to download bunch of other libraries for x86_64).

### Impact
Fission users can run easily fission-cli without any workarounds.

## Solution
This may be a blocker: https://github.com/actions/virtual-environments/issues/2187 though many projects are still able to release m1 binary.

## Others
There's also a notion of a universal binary, not sure what are the limitations https://support.circleci.com/hc/en-us/articles/360056461452-Apple-M1-Apple-Silion-Support-on-CircleCI

**Comment by walkah** [comment]
Hi @LesnyRumcajs ! You're right, we've been waiting (and waiting ... and waiting) for the official github action M1 support to automate builds for M1. 

However, if you are a homebrew user, we do have a tap where we build & upload m1 native versions: https://github.com/fission-suite/homebrew-fission
