### ISSUE TITLE
Need to be able to generate UCANs from the cli 

### ISSUE THREAD

**Issue by therealjeffg** [fission-suite/fission#599]
Use case: web2 web apps like discourse should be able to use the append endpoint to upload data directly to IPFS. For the discourse admin, the desired workflow is that the admin pastes some sort of key or UCAN into the settings page for the (mythical) Discourse / Fission / IPFS upload plugin.

## From a talk discussion:

![image](https://user-images.githubusercontent.com/104315/170761236-3c0ecdfc-a0eb-470e-9abb-ce9fe84c8755.png)

**Comment by walkah** [comment]
Thanks for writing this up! We absolutely want this anyway (for the github action). We have #496 (which is slightly different) but maybe we can close it @expede ?
