### ISSUE TITLE
Server status monitoring / page

### ISSUE THREAD

**Issue by expede** [fission-suite/fission#96]
NB: Feature requests will only be considered if they solve a pain

# Summary

## Problem

Currently manually test that the server is up

### Impact

If the service is down, then no one can use it!

## Solution

* Plug into monitoring server
* Public-facing server status page, or badge on GH

**Comment by bmann** [comment]
Server status on IPFS ;)

**Comment by expede** [comment]
Immutably! What is “up” when it’s a universal constant? 😆 

But seriously, we could serve a static page over IPFS that looks for the “pong” from runfission.com/ping, then sure

**Comment by expede** [comment]
Exists
